services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - postgres-service
      - redis-service

    volumes:
      - .:/app
  postgres-service:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AlbAgRDgqv
      POSTGRES_DB: development
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis-service:
    image: redis:latest
    networks:
      - app-network
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data